### ISSUE TITLE
Create .bin for "releases"? 

### ISSUE THREAD

**Issue by ArcadeHustle** [DragonMinded/naomidoom#1]
I know some folks that want to netboot this, but don't have the capability to compile. Can you generate a release binary?

**Comment by DragonMinded** [comment]
Not yet, I don't want a bunch of different pre-release versions floating around. They tend to generate unnecessary amounts of bug reports for things fixed already.

**Comment by ArcadeHustle** [comment]
Totally understood. **#respect**

**Comment by DragonMinded** [comment]
Okay 1.0 alpha 1 shareware put up, with minimal working basically everything and the version on the test menu.
