### ISSUE TITLE
Error trying to netboot

### ISSUE THREAD

**Issue by camprevail** [DragonMinded/naomidoom#2]
Getting "The game is not acceptable by the main board".  Using `transfergame.exe 192.168.1.5 doom-1.0alpha3.bin`

**Comment by DragonMinded** [comment]
I don't think that's a problem with this code or the compiled binaries. I've netbooted this just fine and so have other testers. Perhaps don't use transfergame? I don't think it sets zero keys properly.

**Comment by camprevail** [comment]
The WAD isn't actually used when netbooting right? Just the bin?

**Comment by DragonMinded** [comment]
No, the WAD is only checked in to aid in "make shareware" without having to source it elsewhere (it can be freely distributed as its a shareware WAD). It gets built into the bin.

**Comment by DragonMinded** [comment]
Did you get your issue resolved? I recommend using my netboot utils instead of transfergame.exe as they have all sorts of extra options and its what I used to test net booting doom: https://github.com/DragonMinded/netboot/

**Comment by camprevail** [comment]
Yeah we're gonna try that next, whenever we get time. I'll reopen the issue if it doesn't work for some reason. Thanks
